version: "3.8"

services:
  keepfocus:
    build:
      context: .
      dockerfile: apps/keepfocus/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
