services:
  keepfocus:
    image: tools-mono/keepfocus
    build:
      context: .
      dockerfile: apps/keepfocus/Dockerfile
    ports:
      - '3000:3000'
    dns:
      - 8.8.8.8
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nully:
    image: tools-mono/nully
    build:
      context: .
      dockerfile: apps/nully/Dockerfile
    ports:
      - '3001:3001'
    dns:
      - 8.8.8.8
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
